import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GraphQLProvider } from "@/components/providers/graphql-provider";
import { I18nProvider } from "@/components/providers/i18n-provider";
import { AdminSidebar } from "@/components/admin-sidebar";
import { AppToaster } from "@/components/ui/app-toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <I18nProvider>
          <GraphQLProvider>
            <div className="flex min-h-screen bg-background">
              <AdminSidebar />
              <main className="flex-1 overflow-auto">{children}</main>
            </div>
            <AppToaster />
          </GraphQLProvider>
        </I18nProvider>
      </body>
    </html>
  );
}
