import { createPubSub } from "graphql-yoga";

export const pubsub = createPubSub();

export const EVENTS = {
  MOBILE_USER_CREATED: "MOBILE_USER_CREATED",
  MOBILE_USER_UPDATED: "MOBILE_USER_UPDATED",
  DEVICE_APPROVAL_STATUS: "DEVICE_APPROVAL_STATUS",
  ACCOUNTS_UPDATED: "ACCOUNTS_UPDATED",
  BENEFICIARIES_UPDATED: "BENEFICIARIES_UPDATED",
  APP_STRUCTURE_UPDATED: "APP_STRUCTURE_UPDATED",
} as const;
